project:
  type: website

website:
  title: "Bits in servicio Scientiae"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - yeti
      - custom.scss
    css: styles.css
