project:
  type: website

website:
  title: "Bits in servicio Scientiae"
  navbar:
    title: false
    collapse: false
    background: rgb(233, 235, 237)
    right:
      - icon: "translate"
        text: " "

      - text: "ast"
        href: /ast
      - text: "en"
        href: /en
      - text: "es"
        href: /es
format:
  html:
    theme: default
    backgroundcolor: rgb(233, 235, 237)
    mainfont: Georgia
    css: styles.css
    linkcolor: rgb(90, 111, 126)
    fontsize: 110%
