project:
  type: website

website:
  title: "Bits in servicio Scientiae"
format:
  html:
    theme:
      - yeti
      - custom.scss
    backgroundcolor: rgb(233, 235, 237)
    mainfont: Georgia
    css: styles.css
