project:
  type: website

website:
  title: "Bits in servicio Scientiae"
format:
  html:
    theme: default
    backgroundcolor: rgb(233, 235, 237)
    mainfont: Georgia
    css: styles.css
    linkcolor: rgb(90, 111, 126)
    fontsize: 110%
    fontcolor: rgb(23,29,13)
